/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import compartilhamento.Global;
import models.Palavra;
import services.PalavraService;

/**
 *
 * @author Tiago Enriquez Tachy
 */
public class TelaConfiguracao extends javax.swing.JFrame {
    
    private TelaPrincipal telaPrincipal;
    private Palavra palavra;
    private PalavraService palavraService;
    
    public TelaConfiguracao(TelaPrincipal telaPrincipal, Palavra palavra) {
        this.telaPrincipal = telaPrincipal;
        this.palavra = palavra;
        this.palavraService = new PalavraService();
        initComponents();
        setLocationRelativeTo(this);
        inserirIcone();
        desabilitarBotaoDesnecessario(palavra);
    }

    /**
     * Creates new form TelaConfiguracao
     */
    public TelaConfiguracao() {
        initComponents();
    }

    /**
     * Desabilita o botão Corrigir se não houver palavra e desabilita o botão
     * Inserir se houver palavra.
     *
     * @param palavra
     */
    private void desabilitarBotaoDesnecessario(Palavra palavra) {
        if (palavra == null) {
            buttonCorrigir.setEnabled(false);
        } else {
            buttonInserir.setEnabled(false);
            textFieldId.setText(String.valueOf(palavra.getId()));
        }
    }

    /**
     * Aciona o método que insere o ícone na barra de título.
     *
     * @throws Exception
     */
    private void inserirIcone() {
        try {
            new Global().logo(this);
        } catch (Exception exception) {
            Mensagem.erro(exception.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        labelId = new javax.swing.JLabel();
        textFieldId = new javax.swing.JTextField();
        labelNome = new javax.swing.JLabel();
        textFieldNome = new javax.swing.JTextField();
        buttonInserir = new javax.swing.JButton();
        buttonCorrigir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configuração");
        setPreferredSize(new java.awt.Dimension(400, 150));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                fechar(evt);
            }
        });

        jPanel1.setMinimumSize(new java.awt.Dimension(400, 120));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 120));
        jPanel1.setRequestFocusEnabled(false);

        labelId.setText("Id");
        labelId.setPreferredSize(new java.awt.Dimension(30, 30));

        textFieldId.setEnabled(false);
        textFieldId.setPreferredSize(new java.awt.Dimension(40, 30));

        labelNome.setText("Nome");
        labelNome.setPreferredSize(new java.awt.Dimension(50, 30));

        textFieldNome.setPreferredSize(new java.awt.Dimension(180, 30));

        buttonInserir.setText("Inserir");
        buttonInserir.setPreferredSize(new java.awt.Dimension(170, 30));
        buttonInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserir(evt);
            }
        });

        buttonCorrigir.setText("Corrigir");
        buttonCorrigir.setPreferredSize(new java.awt.Dimension(170, 30));
        buttonCorrigir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                corrigir(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(buttonInserir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonCorrigir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(textFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(labelNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(textFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonInserir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCorrigir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(210, Short.MAX_VALUE))
        );

        desktopPane.add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 120);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Informa o fechamento desta tela para a tela principal.
     *
     * @param evt
     */
    private void fechar(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_fechar
        if (telaPrincipal != null) {
            telaPrincipal.fecharConfiguracao();
        }
    }//GEN-LAST:event_fechar

    /**
     * Aciona o serviço de inserção de palavra no banco de dados com o nome
     * escrito no campo nome.
     *
     * @param evt
     */
    private void inserir(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserir
        try {
            palavraService.inserir(new Palavra(textFieldNome.getText()));
        } catch (Exception exception) {
            Mensagem.erro(exception.getMessage());
        }
    }//GEN-LAST:event_inserir

    /**
     * Aciona o serviço de correção de palavra no banco de dados.
     *
     * @param evt
     */
    private void corrigir(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_corrigir
        try {
            palavraService.corrigir(new Palavra(Integer.parseInt(textFieldId.getText()), textFieldNome.getText()));
            Mensagem.sucesso("Palavra corrigida com sucedida");
        } catch (Exception exception) {
            Mensagem.erro(exception.getMessage());
        }
    }//GEN-LAST:event_corrigir

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConfiguracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConfiguracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConfiguracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConfiguracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaConfiguracao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCorrigir;
    private javax.swing.JButton buttonInserir;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel labelNome;
    private javax.swing.JTextField textFieldId;
    private javax.swing.JTextField textFieldNome;
    // End of variables declaration//GEN-END:variables

}
