/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import compartilhamento.Global;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import models.Jogo;
import services.JogoService;
import services.PalavraService;

/**
 *
 * @author Tiago Enriquez Tachy
 */
public class TelaJogo extends javax.swing.JFrame {

    private String palavra;
    private Jogo jogo;
    private JogoService jogoService;
    private boolean jogoEmAndamento;
    private List<Jogo> jogos;

    /**
     * Creates new form TelaJogo
     *
     * @param palavra
     */
    public TelaJogo(String palavra) {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        inserirIcone();
        jogos = new ArrayList<>();
        iniciarJogo(palavra);
    }

    /**
     * Inicia um jogo.
     *
     * @param palavra
     */
    private void iniciarJogo(String palavra) {
        jPanel1.setBackground(new Color(255, 191, 128));
        this.palavra = palavra;
        System.out.println(palavra);
        jogo = new Jogo(palavra);
        this.jogoService = new JogoService();
        jogoEmAndamento = true;
        atualizarCampos();
    }

    /**
     * Atualiza os dados na tela.
     */
    private void atualizarCampos() {
        labelNumeroAcertos.setText(String.valueOf(jogo.getAcertos()));
        labelNumeroChances.setText(String.valueOf(jogo.getChances()));
        labelNomePalavraSecreta.setText(String.valueOf(jogo.getPalavraSecreta()));
        jogoEmAndamento = jogo.getAcertos() < palavra.length() && jogo.getChances() > 0;
        labelForca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Erro " + String.valueOf(6 - jogo.getChances()) + ".JPG")));
        mostrarLabels();
    }

    /**
     * Mostra os resultados a depender de se o jogo está em andamento.
     */
    private void mostrarLabels() {
        labelResultado.setVisible(!jogoEmAndamento);
        labelPercentagemAcertos.setVisible(!jogoEmAndamento);
        labelPercentagemVitorias.setVisible(!jogoEmAndamento);
        labelNumeroPercentagemAcertos.setVisible(!jogoEmAndamento);
        labelNumeroPercentagemVitorias.setVisible(!jogoEmAndamento);
        buttonCorrigirPalavra.setVisible(!jogoEmAndamento);
    }

    /**
     * Escreve o resultado na tela.
     */
    private void mostrarResultados() {
        if (jogo.getAcertos() == palavra.length()) {
            labelResultado.setText("Parabéns! Você acertou!");
            jPanel1.setBackground(new Color(128, 191, 128));
            jogo.setVitoria(true);
        } else {
            labelResultado.setText("Que pena! Você errou!");
            jPanel1.setBackground(new Color(255, 128, 128));
        }
    }

    /**
     * Mostra as percentagens de acertos e vitórias ao longo das partidas.
     */
    private void mostrarPercentagens() {
        Object[] percentagens = jogoService.obterPercentagens(jogos, jogo);
        System.out.println("A percentagem de acertos é " + String.valueOf(percentagens[0]));
        labelNumeroPercentagemAcertos.setText(String.valueOf(percentagens[0]));
        labelNumeroPercentagemVitorias.setText(String.valueOf(percentagens[1]));
    }

    /**
     * Aciona o método que insere o ícone na barra de título.
     *
     * @throws Exception
     */
    private void inserirIcone() {
        try {
            new Global().logo(this);
        } catch (Exception exception) {
            Mensagem.erro(exception.getMessage());
        }
    }

    /**
     * Creates new form TelaJogo
     */
    public TelaJogo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        labelAcertos = new javax.swing.JLabel();
        labelChances = new javax.swing.JLabel();
        labelNumeroAcertos = new javax.swing.JLabel();
        labelNumeroChances = new javax.swing.JLabel();
        labelPalavraSecreta = new javax.swing.JLabel();
        labelNomePalavraSecreta = new javax.swing.JLabel();
        labelForca = new javax.swing.JLabel();
        labelLetra = new javax.swing.JLabel();
        textFieldLetra = new javax.swing.JTextField();
        buttonSubmeterLetra = new javax.swing.JButton();
        labelResultado = new javax.swing.JLabel();
        labelPercentagemAcertos = new javax.swing.JLabel();
        labelPercentagemVitorias = new javax.swing.JLabel();
        labelNumeroPercentagemAcertos = new javax.swing.JLabel();
        labelNumeroPercentagemVitorias = new javax.swing.JLabel();
        buttonCorrigirPalavra = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jogo da Forca");

        desktopPane.setPreferredSize(new java.awt.Dimension(2000, 1000));

        jPanel1.setPreferredSize(new java.awt.Dimension(2000, 1000));

        labelAcertos.setText("Acertos");
        labelAcertos.setPreferredSize(new java.awt.Dimension(50, 30));

        labelChances.setText("Chances");
        labelChances.setPreferredSize(new java.awt.Dimension(50, 30));

        labelNumeroAcertos.setPreferredSize(new java.awt.Dimension(30, 30));

        labelNumeroChances.setPreferredSize(new java.awt.Dimension(30, 30));

        labelPalavraSecreta.setText("Palavra Secreta:");
        labelPalavraSecreta.setPreferredSize(new java.awt.Dimension(100, 30));

        labelNomePalavraSecreta.setPreferredSize(new java.awt.Dimension(130, 30));

        labelForca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Erro 0.JPG"))); // NOI18N

        labelLetra.setText("Digite uma letra:");
        labelLetra.setPreferredSize(new java.awt.Dimension(100, 30));

        textFieldLetra.setPreferredSize(new java.awt.Dimension(30, 30));
        textFieldLetra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submeterLetraEnter(evt);
            }
        });

        buttonSubmeterLetra.setText("Submeter letra");
        buttonSubmeterLetra.setPreferredSize(new java.awt.Dimension(250, 30));
        buttonSubmeterLetra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submeterLetra(evt);
            }
        });

        labelResultado.setPreferredSize(new java.awt.Dimension(250, 30));

        labelPercentagemAcertos.setText("Percentagem de acertos");
        labelPercentagemAcertos.setPreferredSize(new java.awt.Dimension(140, 30));

        labelPercentagemVitorias.setText("Percentagem de vitórias");
        labelPercentagemVitorias.setPreferredSize(new java.awt.Dimension(140, 30));

        labelNumeroPercentagemAcertos.setPreferredSize(new java.awt.Dimension(90, 30));

        labelNumeroPercentagemVitorias.setPreferredSize(new java.awt.Dimension(90, 30));

        buttonCorrigirPalavra.setText("Corrigir palavra");
        buttonCorrigirPalavra.setPreferredSize(new java.awt.Dimension(250, 30));
        buttonCorrigirPalavra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                corrigirPalavra(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(583, 583, 583)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonCorrigirPalavra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(labelPercentagemVitorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(labelNumeroPercentagemVitorias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(labelPercentagemAcertos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(labelNumeroPercentagemAcertos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(labelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(labelLetra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(textFieldLetra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelPalavraSecreta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(labelAcertos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(labelNumeroAcertos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(labelChances, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(labelNumeroChances, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(70, 70, 70)
                                    .addComponent(labelForca))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addComponent(labelNomePalavraSecreta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(buttonSubmeterLetra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(1167, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelAcertos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNumeroAcertos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelChances, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNumeroChances, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(labelForca))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPalavraSecreta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNomePalavraSecreta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLetra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldLetra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(buttonSubmeterLetra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(labelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPercentagemAcertos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNumeroPercentagemAcertos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPercentagemVitorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNumeroPercentagemVitorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(buttonCorrigirPalavra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(398, Short.MAX_VALUE))
        );

        desktopPane.add(jPanel1);
        jPanel1.setBounds(0, 0, 2000, 1000);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Aciona os métodos decorrentes da submissão de uma letra ao sistema.
     *
     * @param evt
     */
    private void submeterLetra(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submeterLetra
        try {
            if (jogoEmAndamento) {
                jogo = jogoService.conferirLetra(textFieldLetra.getText().charAt(0), jogo);
                atualizarCampos();
                if (!jogoEmAndamento) {
                    buttonSubmeterLetra.setText("Outra partida");
                    atualizarCampos();
                    mostrarResultados();
                    labelNomePalavraSecreta.setText(palavra);
                    mostrarPercentagens();
                }
            } else {
                iniciarJogo(new PalavraService().sortear());
                buttonSubmeterLetra.setText("Submeter letra");
            }
            textFieldLetra.setText("");
        } catch (Exception exception) {
            Mensagem.erro(exception.getMessage());
        }
    }//GEN-LAST:event_submeterLetra

    /**
     * Encaminha para tela de configuração no modo correção de palavra.
     *
     * @param evt
     */
    private void corrigirPalavra(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_corrigirPalavra
        try {
            new TelaConfiguracao(null, new PalavraService().procurar(palavra)).setVisible(true);
        } catch (Exception exception) {
            Mensagem.erro(exception.getMessage());
        }
    }//GEN-LAST:event_corrigirPalavra

    /**
     * Aciona o método para submeter letra através da tecla Enter do teclado.
     *
     * @param evt
     */
    private void submeterLetraEnter(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submeterLetraEnter
        submeterLetra(evt);
    }//GEN-LAST:event_submeterLetraEnter

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaJogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCorrigirPalavra;
    private javax.swing.JButton buttonSubmeterLetra;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelAcertos;
    private javax.swing.JLabel labelChances;
    private javax.swing.JLabel labelForca;
    private javax.swing.JLabel labelLetra;
    private javax.swing.JLabel labelNomePalavraSecreta;
    private javax.swing.JLabel labelNumeroAcertos;
    private javax.swing.JLabel labelNumeroChances;
    private javax.swing.JLabel labelNumeroPercentagemAcertos;
    private javax.swing.JLabel labelNumeroPercentagemVitorias;
    private javax.swing.JLabel labelPalavraSecreta;
    private javax.swing.JLabel labelPercentagemAcertos;
    private javax.swing.JLabel labelPercentagemVitorias;
    private javax.swing.JLabel labelResultado;
    private javax.swing.JTextField textFieldLetra;
    // End of variables declaration//GEN-END:variables

}
